### ISSUE TITLE
ggplot won't plot

### ISSUE THREAD

**Issue by eriklarsen4** [camdenk/mlbplotR#1]
Following your code, I'm required to install ggimage to use geom_image to map and plot the logos. With that, I cannot control the transparency of the images. Otherwise R/ggplot does not recognize the png files in the dataframe object scraped from ESPN ->

I get an error: 

Error in if (is.raw(img) || tools::file_ext(img) != "svg") { : 
  missing value where TRUE/FALSE needed

Curious why "team_savant_abbr" is titled as it is

**Comment by camdenk** [comment]
The parameter is (poorly) named "team_savant_abbr" because I designed the geoms to be easily used with Statcast data from baseballsavant.com. Within those raw data files, each team has their team abbreviation but they aren't uniform across different sources (e.g. the White Sox are labeled as CWS in Statcast but are CHW on Baseball-Reference). Without knowing what data you're passing in, I'm betting those misaligned abbreviations are what's causing your error.


The abbreviations under the primary column are those that can be passed into the geom successfully. 

team_name | team_primary_abbr | team_secondary_abbr
-- | -- | --
Arizona Diamondbacks | ARI | ARI
Atlanta Braves | ATL | ATL
Baltimore Orioles | BAL | BAL
Boston Red Sox | BOS | BOS
Chicago Cubs | CHC | CHC
Chicago White Sox | CWS | CHW
Cincinnati Reds | CIN | CIN
Cleveland Guardians | CLE | CLE
Colorado Rockies | COL | COL
Detroit Tigers | DET | DET
Houston Astros | HOU | HOU
Kansas City Royals | KC | KC
Los Angeles Angels | LAA | LAA
Los Angeles Dodgers | LAD | LAD
Miami Marlins | MIA | MIA
Milwaukee Brewers | MIL | MIL
Minnesota Twins | MIN | MIN
New York Mets | NYM | NYM
New York Yankees | NYY | NYY
Oakland Athletics | OAK | OAK
Philadelphia Phillies | PHI | PHI
Pittsburgh Pirates | PIT | PIT
San Diego Padres | SD | SD
San Francisco Giants | SF | SF
Seattle Mariners | SEA | SEA
St. Louis Cardinals | STL | STL
Tampa Bay Rays | TB | TB
Texas Rangers | TEX | TEX
Toronto Blue Jays | TOR | TOR
Washington Nationals | WSH | WAS

**Comment by camdenk** [comment]
This certainly highlights why I need to build in an abbreviation check/correction function and update the parameter names!

**Comment by eriklarsen4** [comment]
awesome! yeah, I was using BR abbrvs, so I'll go back and check. interestingly, I got it to work with ggimage, but alpha wouldn't map, so I punted. I love how all the websites have their own abbrvs and name spellings. such a nightmare when you're pulling a lot of data and combining from multiple sources.

good stuff, dude.

**Comment by camdenk** [comment]
Appreciate it! I'll probably rework the MLB_Logos_Colors file to include each website's abbreviation of choice to make for easy joining of data frames and implement an "abbreviation checker" to help catch some of these troubles on the back end before plotting.
